<div id="menu">
	<ul id="sddm">
		<li><a href="index.php">Home</a></li>
		<li><a href="day_at_camp.php" onmouseover="mopen('m2')" onmouseout="mclosetime()">The Camp</a>
			<div id="m2" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
				<a href="day_at_camp.php">A Day at Camp</a>
				<a href="activities.php">Activities</a>
                <a href="location.php">Location</a>
                <a href="photos.php">Photos</a>
            </div>
        </li>
        <li><a href="who_we_are.php" onmouseover="mopen('m3')" onmouseout="mclosetime()">About Us</a>
        	<div id="m3" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
            	<a href="who_we_are.php">Who We Are</a>
                <a href="testimonials.php">Testimonials</a>
            </div>
        </li>
        <li><a href="get_involved.php" onmouseover="mopen('m4')" onmouseout="mclosetime()">Get Involved</a>
       		<div id="m4" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
            	<a href="donate.php">Donate</a>
            	<a href="contact_us.php">Contact Us</a>
        	</div>
        </li>
    </ul>
	<div style="clear:both"></div>
</div>
     