	 <div id="menu">
	 <ul id="sddm">
	 
	 <li><a href="index.php">Home</a>
	 </li>
	 
	 <li><a href="day_at_camp.php" onmouseover="mopen('m2')" onmouseout="mclosetime()">The Camp</a>
	 <div id="m2" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
	 <a href="day_at_camp.php">A Day at Camp</a>
	 <a href="activities.php">Activities</a>
	 <a href="location.php">Location</a>
	 <a href="photos.php">Photos</a>
	 </div>
	 </li>
	 
	 <li><a href="who_we_are.php" onmouseover="mopen('m3')" onmouseout="mclosetime()">About Us</a>
	 <div id="m3" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
	 <a href="who_we_are.php">Who We Are</a>
	 <a href="testimonials.php">Testimonials</a>
	 </div>
	 </li>
	
	 <li><a href="get_involved.php" onmouseover="mopen('m4')" onmouseout="mclosetime()">Get Involved</a>
	 <div id="m4" onmouseover="mcancelclosetime()" onmouseout="mclosetime()">
	 <a href="donate.php">Donate</a>
	 <a href="contact_us.php">Contact Us</a>
	 </div>
	 </li>
	 
	 </ul>
	 <div style="clear:both">
	 </div>
	 </div>
     
     </div>
	</div>
	<div id="main">
	 <div id="sidebar">
        	<img alt="logo" id="logo" src="images/camplogo_sm.png" />
        	<p style="text-align:center"><a href="https://www.peacecorps.gov/index.cfm?shell=donate.contribute.projDetail&projdesc=685-163" target="_blank"><img src="images/donate_now.png" /></a></p>
	 <p class="sidebar_p">We're getting ready for this year's camp already! Fundraising has begun, planning is in full swing, and we're looking forward to an even better year than last!</p>
            <!--<p>Check out the video from last year's camp <a href="">here</a>!</p>-->
            <a href="http://pcsenegal.org" target="_blank"><img id="pcsenegal" alt="pcsenegal" src="images/pcsenegal_project_190.jpg" /></a>
	 </div>
     