<img alt="logo" id="logo" src="images/camplogo_200.gif" />
<p style="text-align:center">


</p>

<p class="sidebar_p">Thanks to everyone who donated to this year's camp! We've reached our goal, and final planning is in full swing. Stay tuned here for updates as the camp unfolds.</p>

<p><a href="http://www.youtube.com/watch?v=GACauzro2h0">Check out the video from last year's camp!</a></p>

<p>This is a Peace Corps Senegal project.</p>
<div style="text-align:center"><a href="http://pcsenegal.org" target="_blank"><img id="pcsenegal" alt="pcsenegal" src="images/pcsenegal_project_190.jpg" /></a></div>